### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by HolgerStenberg** [HolgerStenberg/KTH_KEX-jobb_2021#6]
- [x] Background
- [x] Goals
- [x] Time plan explanation
- [x] Risk analysis
- [x] Project Model 

Organisation:
- [x] Project group
- [x] Sponsors
- [x] Workflow

Additional files:
- [x] WBS
- [x] Timeplan

**Comment by HolgerStenberg** [comment]
doing workflow

**Comment by HolgerStenberg** [comment]
Detta projekt startades i samband med kursen EH1010 Elektroprojekt vid Kungliga Tekniska Högskolan i Stockholm. Samtliga kursmål är relaterade till att studenterna ska lära sig att arbeta i projektform och utveckla kommunikativa och planeringsmässiga färdigheter. Samtliga projektmedlemmar studerar första året på civilingenjörsprogrammet i elektroteknik.

Grunden till detta projekt ligger i ett uppdrag, givet av kursansvarig Liv Gingnell, att lösa ett valfritt vardagsproblem. Arbetsgruppen sammanställdes och ett problem diskuterades fram. Därefter inleddes arbetet med att finna en lösning till problemet ifråga. 

Färska kryddor används i stor utsträckning i all världens mat. Det är därför vanligt att affärer säljer flertalet kryddväxter i plastkrukor. Detta görs för att konsumenter inte ska behöva nöja sig med torkade eller frysta alternativ som inte bidrar till samma smakupplevelse. 
Problemet som ämnas lösas med detta projekt är den korta livslängden som dessa färska kryddor har då de inte bevattnas eller får tillräckligt med ljus i hemmet. För att få kryddorna att överleva krävs i nuläget att en konsument måste ägna tid och energi på växternas välmående. Projektgruppen har därför som uppdrag att ta fram en robot som lösning på detta vardagsproblem. Denna robot möjliggör att färska kryddor kommer överleva utan uppsikt av konsumenten samt vara oberoende av naturligt ljus. 

Att få färska kryddor att hålla längre med hjälp av roboten ger möjligheten för matlagare att nyttja färska kryddor flera gånger under dess livslängd, vilket är ekonomiskt gynnsamt. Ur ett hållbarhetsperspektiv ges även stor vinst i att fullt ätbar mat inte kastas för att kryddor vissnar tidigare än vad de skulle behöva göra om roboten användes.  

Som tidigare nämnt går projektetuppgiften ut på att lösa ett vardagsproblem med hjälp av en robot. Utöver detta krävs att roboten är fysisk och att den använder sig av en Arduino Uno som styrenhet. 
Under de första årets studier har gruppmedlemmarna läst ämnesspecifika kurser  som resulterat i nödvändiga kunskaper för att kunna genomföra projektet.

**Comment by HolgerStenberg** [comment]
doing goals!

**Comment by HolgerStenberg** [comment]
doing time plan

**Comment by HolgerStenberg** [comment]
- [x] add comment about us having two courses in the past regarding projects

**Comment by HolgerStenberg** [comment]
- [ ] fix how to achieve goals and when to achieve them
- [x] it is called business goals, change please

**Comment by HolgerStenberg** [comment]
<img width="1092" alt="Screenshot 2021-02-09 at 19 59 52" src="https://user-images.githubusercontent.com/51445907/107413740-62bb7300-6b11-11eb-86da-3d0df52065f1.png">
look for this before submitting!
